stages:
  train:
    cmd: python -m src.train.train
    deps:
      - src/
      - src/params.yaml
      - data/raw/Reviews.csv
      - data/raw/training.1600000.processed.noemoticon.csv
    outs:
      - models/
    metrics:
      - metrics.json:
          cache: false